spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-wallet/**, /customer/**
        - id: seller-service
          uri: lb://seller-service
          predicates:
            - Path=/seller/**
      discovery:
        locator:
          enabled: true
server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true