spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/seller/**, /customer/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/customer-transaction/**, /seller-transaction/**
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/customer-wallet/**, /seller-wallet/**
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
server:
  port: 8889

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true