name: Build

on:
  push:
    branches:
      - test-actions

env:
  REGISTRY: docker.io
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  go_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["url-shortener-service"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Install Dependencies
        working-directory: ${{ matrix.service }}
        run: go mod download

      - name: Build with golang
        working-directory: ${{ matrix.service }}
        run: go build -o app

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract image metadata for ${{ matrix.service }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.service }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  java_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["eureka-server", "api-gateway", "user-service", "product-service", "transaction-service", "wallet-service", "notification-service"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "corretto"

      - name: Build with Maven
        working-directory: ${{ matrix.service }}
        run: mvn -B package -DskipTests --file pom.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract image metadata for ${{ matrix.service }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.service }}

      - name: Build and push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}